[versions]
# Project
compileSdk = "35"
minSdk = "28"
targetSdk = "35"
versionCode = "1"
versionName = "1.0.0"
reactivestate = "6.0.0-preview.19"

# Core Libraries
agp = "8.11.1"
appcompat = "1.7.1"
coreKtx = "1.16.0"
kotlin = "2.2.0"
serialization = "1.9.0"
dokka = "2.0.0"
detekt = "1.23.8"
compose = "1.8.2"
desugarJdkLibs = "2.1.5"

# Compose Libraries
activityCompose = "1.10.1"
composeBom = "2025.06.01"
navigationCompose = "2.9.0-beta03"

# Third Party
ktor = "3.2.3"
darwin= "3.0.0"
okhttp= "4.12.0"

# Testing
espressoCore = "3.6.1"
googleTruth = "1.4.4"
junit = "4.13.2"
junitJupiter = "5.10.0"
junitVersion = "1.2.1"
coroutines = "1.10.2"
mockk = "1.14.5"
turbine = "1.0.0"
napierVersion = "2.7.1"

[libraries]

datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.2"
io-core = "org.jetbrains.kotlinx:kotlinx-io-core:0.8.0"
coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
logger-napier = { module = "io.github.aakira:napier", version.ref = "napierVersion" }

# Core Libraries
androidx-startup = "androidx.startup:startup-runtime:1.2.0"
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-xml = "io.github.pdvrieze.xmlutil:serialization:0.91.2"

# Compose Libraries
androidx-activity = { module = "androidx.activity:activity-ktx", version = "activityCompose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
compose-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# Third Party Libraries
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialisation = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-kotlinx-serializable = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
okhttp-tls = {module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttp"}

# ReactiveState
reactivestate-bom = { module = "com.ensody.reactivestate:reactivestate-bom", version.ref = "reactivestate" }
reactivestate-android = { module = "com.ensody.reactivestate:reactivestate-android", version.ref = "reactivestate" }
reactivestate-android-test = { module = "com.ensody.reactivestate:reactivestate-android-test", version.ref = "reactivestate" }
reactivestate-compose = { module = "com.ensody.reactivestate:reactivestate-compose", version.ref = "reactivestate" }
reactivestate-core = { module = "com.ensody.reactivestate:reactivestate-core", version.ref = "reactivestate" }
reactivestate-core-test = { module = "com.ensody.reactivestate:reactivestate-core-test", version.ref = "reactivestate" }

# Unit Testing Libraries
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
google-truth = { module = "com.google.truth:truth", version.ref = "googleTruth" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref="okhttp" }

# Ktor Server
ktor-server-core-jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty-jvm = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-logging-jvm = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktor" }
ktor-server-cors-jvm = { module = "io.ktor:ktor-server-cors-jvm", version.ref = "ktor" }

# Instrumentation Testing Libraries
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

gradle-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-cocoapods = { module = "org.jetbrains.kotlin.native.cocoapods:org.jetbrains.kotlin.native.cocoapods.gradle.plugin", version.ref = "kotlin" }
gradle-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-kotlin-compose = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
gradle-jetbrains-compose = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose" }
gradle-kotlin-jvm = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
gradle-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.33.0" }
gradle-serialization = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }

desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
kotlin-test-main = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version = "1.5.0" }
mockk = { module = "io.mockk:mockk", version = "1.14.5" }
robolectric = { module = "org.robolectric:robolectric", version = "4.15.1" }

[plugins]
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependencyCheck = { id = "org.owasp.dependencycheck", version = "12.1.3" }

[bundles]
unit-tests = ["junit", "mockk-android", "google-truth"]
instrumentation-tests = ["androidx-junit", "androidx-espresso-core"]
